version: "3.9"

services:
  frontend:
    build: .
    container_name: zerocarbs_c
    ports:
      - "5173:5173"
    volumes:
      - ".:/app"
      - "/app/node_modules"
    stdin_open: true
    tty: true
    working_dir: /app
